---
build:
  variables:
    GOPRIVATE: git.example.com/*
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - mkdir -p ${HOME}
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_BUILD_TOKEN}" > ${HOME}/.netrc
  - >-
    /kaniko/executor
    --context "${CI_PROJECT_DIR}"
    --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
  - if: $CI_COMMIT_TAG
